version: "3"

services:
  user-service:
      build:
        context: ./user
        dockerfile: Dockerfile
      container_name: "user-service"
      entrypoint: /usr/src/entypoint
      ports:
        - 28017:27017
      volumes:
        - ./user:/usr/src/app
        - ./entrypoints/user-service-entrypoint:/usr/src/entypoint
        - ./data/user/db:/data/db
      environment:
        - NODE_ENV=docker-dev
      restart: always
  book-service:
      build:
        context: ./book
        dockerfile: Dockerfile
      container_name: "book-service"
      entrypoint: /usr/src/entypoint
      ports:
        - 28018:27017
      volumes:
        - ./book:/usr/src/app
        - ./entrypoints/book-service-entrypoint:/usr/src/entypoint
        - ./data/book/db:/data/db
      environment:
        - NODE_ENV=docker-dev
      restart: always
  api-gateway-service:
      build:
        context: ./api-gateway
        dockerfile: Dockerfile
      container_name: "api-gateway-service"
      entrypoint: /usr/src/entypoint
      volumes:
        - ./api-gateway:/usr/src/app
        - ./entrypoints/api-gateway-service-entypoint:/usr/src/entypoint
      environment:
        - NODE_ENV=docker-dev
      links:
        - user-service
        - book-service
      restart: always
  nginx-proxy:
      image: nginx:latest
      links:
        - api-gateway-service
      ports:
        - 80:80
      volumes:
        - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      restart: always