version: "3"

services:
  user-service:
      build:
        context: ./user
        dockerfile: Dockerfile
      container_name: "user-service"
      entrypoint: /usr/src/entypoint
      ports:
        - 3001:3001
        - 28017:27017
      volumes:
        - ./user:/usr/src/app
        - ./entrypoints/user-service-entrypoint:/usr/src/entypoint
        - ./data/user/db:/data/db
      environment:
        - NODE_ENV=docker-dev
      restart: always
  book-service:
      build:
        context: ./book
        dockerfile: Dockerfile
      container_name: "book-service"
      entrypoint: /usr/src/entypoint
      ports:
        - 3002:3002
        - 28018:27017
      volumes:
        - ./book:/usr/src/app
        - ./entrypoints/book-service-entrypoint:/usr/src/entypoint
        - ./data/book/db:/data/db
      environment:
        - NODE_ENV=docker-dev
      restart: always